#!/usr/bin/env python3
"""
Blackboard Scan State Tracker (Client-side)

This module tracks BB scans generated by Node A agents and updates shared state
for use by Node B/Node C in skip decision logic. It's called periodically after
successful BB scans to ensure downstream agents can perform fast-fail path checks.

Integration with discord-chat.js flow:
  1. Discord send → scan_id from BB
  2. Post-scan hook in discord-chat.js calls this script
  3. Shared state updated with new scan entry
  4. Other agents poll for skips via verify_scan_ptr.py

Usage as a library:
    from state_sync_client import update_scan_state, make_scan_entry
    
Usage standalone:
    python state_sync_client.py --update --scan-id SCANNER_ID --hash SHA16
"""

import json
from datetime import datetime, timezone


def find_or_create_state_file(path="/droid/repos/cl_shared/state_sync_client.json"):
    """Find or create the shared state file."""
    from pathlib import Path
    p = Path(path)
    
    if not p.exists():
        # Initialize with minimal schema
        initial = {
            "scans": [],
            "meta": {"created_utc": datetime.now(timezone.utc).isoformat()}
        }
        p.write_text(json.dumps(initial, indent=2))
        print(f"[INIT] Created {path}")
        return str(p)
    
    return str(p)


def update_scan_state(scan_id, context_hash_sha256_prefix=None, metadata=None):
    """Update shared state after completing a BB scan."""
    
    path = find_or_create_state_file()
    
    with open(path, 'r') as f:
        data = json.load(f)
    
    entry = {
        "id": scan_id,
        "timestamp_utc": datetime.now(timezone.utc).isoformat(),
        "context_key": context_hash_sha256_prefix or "unknown",
    }
    
    if metadata:
        entry.update(metadata)
    
    # Prepend to scans list (most recent first)
    if "scans" not in data:
        data["scans"] = []
    
    data["scans"].insert(0, entry)
    
    # Limit history to last 100 entries to avoid bloat
    if len(data["scans"]) > 100:
        data["scans"] = data["scans"][:100]
    
    with open(path, 'w') as f:
        json.dump(data, f, indent=2)
    
    print(f"[STATE] Updated bb_sync state:\n"
          f"  - Scan ID: {scan_id}\n"
          f"  - Entries stored: {len(data['scans'])}")


def mark_hash(scan_id, hash_prefix):
    """Helper for updating with hash from discord-chat.js hook."""
    update_scan_state(scan_id, context_hash_sha256_prefix=hash_prefix.upper())


def scan_history(limit=None):
    """Query existing BB scan history."""
    path = find_or_create_state_file()
    
    with open(path, 'r') as f:
        data = json.load(f)
    
    scans = data.get("scans", [])
    
    if limit and len(scans) > limit:
        scans = scans[:limit]
    
    return {
        "path": path,
        "count": len(scans),
        "history": scans
    }


if __name__ == "__main__":
    import argparse
    
    parser = argparse.ArgumentParser(description="Update or query BB sync state")
    subparsers = parser.add_subparsers(dest="command", help="Commands")
    
    # Update command
    upd_parser = subparsers.add_parser("update", help="Add scan to shared state")
    upd_parser.add_argument("--id", required=True, help="Scan ID (e.g., SCANNER_ID_... )")
    upd_parser.add_argument("--hash-prefix", default="", help="SHA-256 prefix for matching")
    upd_parser.add_argument("--state-path", help="Custom state file location")
    
    # Query command
    q_parser = subparsers.add_parser("query", help="Query existing history")
    q_parser.add_argument("--limit", type=int, default=10, help="Max entries to show")
    
    args = parser.parse_args()
    
    if args.command == "update":
        update_scan_state(args.id, args.hash_prefix)
    elif args.command == "query":
        result = scan_history(limit=args.limit)
        print(f"[QUERY] {result['path']} ({result['count']} total)")
        for entry in reversed(result["history"]):  # Show oldest first
            print(f"  - {entry['id']}: {entry.get('context_key', 'N/A')} @ {entry['timestamp_utc']}")
